require("itemScripts/characters.lua")
require("itemScripts/item_greek_ares.lua")
require("itemScripts/item_greek_demeter.lua")
require("itemScripts/item_greek_dionysus.lua")
require("itemScripts/item_greek_hades.lua")
require("itemScripts/item_greek_poseidon.lua")